on: [push]

jobs:
  heroku_vars_comparator_job:
    runs-on: ubuntu-latest
    name: Compare_vars_mt_dev
    steps:
      - name: compare
        id: compare
        uses: raag/heroku_vars_comparator@v1.0.2
        with:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          APP_1: mt-portal-dev
          APP_2: puk-dev
